/*
  Seed ngữ pháp Minna no Nihongo N5 từ tài liệu người dùng cung cấp:
  "List ngữ pháp N5.pdf".

  Kết quả: 1 khóa học, 25 section (Bài 1-25), 94 grammar content.
  Chạy database_language_center_mysql.sql trước file này.
  Có thể chạy lại file mà không tạo dữ liệu trùng.
*/

USE LanguageCenterDB;

START TRANSACTION;

-- Remove only the synthetic 50-lesson dataset generated by the previous seed.
DELETE content
FROM course_content content
JOIN course_section section ON section.id = content.section_id
JOIN course old_course ON old_course.id = section.course_id
WHERE old_course.course_code = 'JA-MINNA-50';

DELETE section
FROM course_section section
JOIN course old_course ON old_course.id = section.course_id
WHERE old_course.course_code = 'JA-MINNA-50';

DELETE FROM course WHERE course_code = 'JA-MINNA-50';

SELECT lv.id INTO @minna_n5_level_id
FROM level lv
JOIN language lg ON lg.id = lv.language_id
WHERE lg.language_code = 'JA' AND lv.level_code = 'N5'
LIMIT 1;

INSERT INTO course (
    level_id, course_code, course_name, slug, short_description, description,
    target_audience, prerequisites, learning_outcomes, syllabus_summary,
    tuition_fee, total_sessions, duration_hours, status, publication_status,
    published_at, is_featured, created_at, updated_at
)
SELECT
    @minna_n5_level_id,
    'JA-MINNA-N5-GRAMMAR',
    'Ngữ pháp Minna no Nihongo N5',
    'ngu-phap-minna-no-nihongo-n5',
    'Tổng hợp 94 điểm ngữ pháp N5 theo 25 bài Minna no Nihongo.',
    'Khóa tham khảo ngữ pháp sơ cấp, mỗi nội dung gồm công thức, nghĩa và ví dụ.',
    'Người mới học tiếng Nhật hoặc đang ôn JLPT N5.',
    'Nên biết Hiragana và Katakana cơ bản.',
    'Nắm được các mẫu câu và cấu trúc ngữ pháp trọng tâm ở trình độ N5.',
    '25 bài với 94 điểm ngữ pháp được tải theo từng section.',
    0, 25, 50, 'ACTIVE', 'PUBLISHED', NOW(), TRUE, NOW(), NOW()
WHERE @minna_n5_level_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM course WHERE course_code = 'JA-MINNA-N5-GRAMMAR'
  );

SELECT id INTO @minna_n5_course_id
FROM course
WHERE course_code = 'JA-MINNA-N5-GRAMMAR'
LIMIT 1;

INSERT INTO course_section (course_id, title, description, display_order)
WITH RECURSIVE lesson_numbers AS (
    SELECT 1 AS lesson_number
    UNION ALL
    SELECT lesson_number + 1 FROM lesson_numbers WHERE lesson_number < 25
)
SELECT
    @minna_n5_course_id,
    CONCAT('Bài ', lesson_number),
    CONCAT('Các điểm ngữ pháp N5 thuộc bài ', lesson_number, '.'),
    lesson_number
FROM lesson_numbers
WHERE @minna_n5_course_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM course_section existing_section
      WHERE existing_section.course_id = @minna_n5_course_id
        AND existing_section.display_order = lesson_numbers.lesson_number
  );

DROP TEMPORARY TABLE IF EXISTS minna_n5_grammar_seed;

CREATE TEMPORARY TABLE minna_n5_grammar_seed (
    lesson_number      INT NOT NULL,
    item_order         INT NOT NULL,
    grammar_pattern    VARCHAR(500) NOT NULL,
    meaning_text       TEXT NOT NULL,
    example_text       TEXT NULL,
    PRIMARY KEY (lesson_number, item_order)
);

INSERT INTO minna_n5_grammar_seed
    (lesson_number, item_order, grammar_pattern, meaning_text, example_text)
VALUES
(1, 1, 'N1 は N2 です', 'N1 là N2.', 'わたしは アン・ミンです。'),
(1, 2, 'N1 の N2', 'N2 của N1.', 'ミちゃんは わたしのねこです。'),
(1, 3, 'N1 は N2 ですか', 'N1 là N2 phải không?', 'ミンさんは かんこくじんですか。'),
(1, 4, 'N1 は N2 ではない（じゃない）です', 'N1 không phải N2.', 'わたしは かんこくじんじゃないです。'),
(1, 5, 'N1 も N2 です', 'N1 cũng là N2.', 'わたしも 二十さいです。'),

(2, 1, 'これ／それ／あれ は N です', 'Đây, đó hoặc kia là N.', 'これは かばんです。'),
(2, 2, 'N1 の N2（nội dung／nơi làm việc）', 'N2 nói về N1 hoặc N2 thuộc, làm việc tại N1.', 'あれは 日本語の本です。まことさんは おおさかだいがくのせんせいです。'),
(2, 3, 'この／その／あの N', 'Cái N này, đó hoặc kia.', 'この パソコンです。'),
(2, 4, 'N1 ですか、N2 ですか', 'Là N1 hay N2?', 'これは くまですか、いぬですか。'),

(3, 1, 'ここ／そこ／あそこ は N です', 'Ở đây, đó hoặc kia là N.', 'ここは だいがくです。'),
(3, 2, 'N は địa điểm です', 'N ở tại địa điểm được nói đến.', 'ワインのうりばは 3階です。'),
(3, 3, 'N1 の N2（xuất xứ）', 'N2 có xuất xứ hoặc thuộc N1.', 'あれは ドイツのくるまです。'),
(3, 4, '～いくら', 'Bao nhiêu tiền?', 'この パソコンは いくらですか。'),

(4, 1, '～時～分です', 'Diễn đạt giờ và phút.', 'ごご 7時30分です。'),
(4, 2, 'N は ～曜日です', 'N là thứ trong tuần.', 'きょうは 月曜日です。'),
(4, 3, 'N（に）V', 'Làm hành động V vào thời điểm N.', 'きょう 8時半に おきました。'),
(4, 4, '～から～までです', 'Từ một thời điểm hoặc địa điểm đến một thời điểm hoặc địa điểm.', 'ぎんこうから かいしゃまでです。'),

(5, 1, 'N へ 行きます／来ます／帰ります', 'Đi, đến hoặc về N.', 'かいしゃへ 行きます。'),
(5, 2, 'N（phương tiện）で 行きます／来ます／帰ります', 'Đi, đến hoặc về bằng phương tiện N.', 'バスで 学校へ 行きます。'),
(5, 3, 'N（người）と 行きます／来ます／帰ります', 'Đi, đến hoặc về cùng người N.', 'うちへ ともだちと 帰ります。'),
(5, 4, 'N（thời gian）に 行きます／来ます／帰ります', 'Đi, đến hoặc về vào thời gian N.', '10月3日に 日本へ 行きます。'),

(6, 1, 'N を Vます', 'Thực hiện hành động V với tân ngữ N.', 'コーヒーを のみます。'),
(6, 2, 'N で Vます', 'Thực hiện hành động V tại N.', 'スーパーで くだものを かいます。'),
(6, 3, 'Vませんか', 'Mời hoặc rủ ai đó cùng làm V.', '晩ご飯を 食べませんか。'),

(7, 1, 'N で Vます（công cụ）', 'Làm V bằng công cụ hoặc phương tiện N.', 'はさみで かみを きります。'),
(7, 2, 'S は N1 に N2 を あげます', 'S cho hoặc tặng N1 vật N2.', '田中さんは こいびとに プレゼントを あげます。'),
(7, 3, 'N1 に N2 を もらいます', 'Nhận N2 từ N1.', 'こいびとは 田中さんに プレゼントを もらいます。'),
(7, 4, 'もう Vました', 'Đã làm V rồi.', 'もう 晩ご飯を 食べました。'),

(8, 1, 'N は Aい／Aな です', 'N có tính chất A.', 'このくるまは 高いです。'),
(8, 2, 'そして、～', 'Và hoặc hơn nữa.', 'つくえに おかしが 五つ あります。'),
(8, 3, '～が、～', 'Có N2 với số lượng ở N1.', 'ちゅうしゃじょうは くるまが 2だい あります。'),
(8, 4, 'N1 は Aい／Aな N2 です', 'Chỉ có N.', '冷蔵庫は おかしだけです。'),

(9, 1, 'N が 好き／嫌いです', 'Thích hoặc ghét N.', 'おにぎらずが すきです。'),
(9, 2, 'N が 分かります', 'Hiểu hoặc biết N.', '日本語が わかります。'),
(9, 3, 'どんな N が A ですか', 'Hỏi N nào hoặc N như thế nào.', 'どんな音楽が 好きですか。'),
(9, 4, '～から、～', 'Vì nguyên nhân phía trước nên có kết quả phía sau.', 'りょうりが 苦手ですから、よく 店で かいます。'),

(10, 1, 'N が あります／います', 'Có N; あります dùng cho vật, います dùng cho người hoặc động vật.', 'じどうはんばいきが あります。'),
(10, 2, 'N1 の N2（vị trí）', 'N2 là vị trí so với N1.', 'ねこは いぬの まえです。'),
(10, 3, 'N1 に N2 が あります／います', 'Có N2 ở N1.', '喫茶店のとなりに ほんやが あります。'),
(10, 4, 'N1 は N2 に あります／います', 'N1 ở tại N2.', 'ミラさんの さいふは いえの なかに あります。'),
(10, 5, '～や～など', 'Liệt kê một số đại diện với nghĩa những thứ như N1, N2.', 'けさ パンや たまごなどを たべました。'),

(11, 1, 'Lượng từ', 'Cách đếm đồ vật, máy móc, vật mỏng và người.', 'りんごを 三つ かいました。'),
(11, 2, 'Khoảng thời gian／～かい', 'Làm V trong khoảng thời gian hoặc số lần trong một khoảng thời gian.', '日本語を 三ヶ月間 勉強しました。'),

(12, 1, 'Aな／N でした・Aいかったです', 'Dạng quá khứ của tính từ và danh từ.', 'いいてんきでした。とても おもしろかったです。'),
(12, 2, 'N1 は N2 より A です', 'N1 có tính chất A hơn N2.', 'わたしは さとうさんより 背が高いです。'),
(12, 3, 'N1 と N2 と どちらが A ですか', 'Hỏi N1 và N2 thì cái nào có tính chất A hơn.', 'でんしゃと バスと どちらが べんりですか。'),
(12, 4, 'N の中で N1 が いちばん A です', 'Trong phạm vi N, N1 có tính chất A nhất.', '彼女は クラスの中で 字が一番きれいです。'),

(13, 1, 'N が ほしいです', 'Muốn có N.', 'あたらしい くつが ほしいです。'),
(13, 2, 'N を Vたいです', 'Muốn làm hành động V.', 'あついですから、シャワーを あびたいです。'),
(13, 3, 'Địa điểmへ Vます／N に 行きます', 'Đi đến một địa điểm để làm V hoặc thực hiện N.', 'しんじゅくへ 買い物に 行きます。'),

(14, 1, 'Phân loại nhóm động từ', 'Phân biệt động từ nhóm 1, nhóm 2 và nhóm 3.', '行きます・食べます・します。'),
(14, 2, 'Vて', 'Cách chia động từ sang thể て.', '行きます → 行って。'),
(14, 3, 'Vてください', 'Hãy làm V.', 'どうぞ、これを 飲んでください。'),
(14, 4, 'Vています', 'Đang thực hiện hành động V.', '今 えいがを 見ています。'),
(14, 5, 'Vましょうか', 'Đề nghị làm V giúp người khác.', 'エアコンを けしましょうか。'),

(15, 1, 'Vてもいいですか', 'Làm V có được không?', 'カードを つかってもいいですか。'),
(15, 2, 'Vてはいけません', 'Không được làm V.', '大きい声で 話してはいけません。'),
(15, 3, 'Vています（trạng thái）', 'Diễn tả trạng thái là kết quả của một hành động.', 'たなかさんは 結婚しています。'),

(16, 1, 'V1て、V2て、～Vます', 'Liệt kê các hành động theo thứ tự xảy ra.', 'ご飯を食べて、ゲームをして、それから宿題をします。'),
(16, 2, 'V1てから、V2', 'Sau khi làm V1 thì làm V2.', 'シャワーを 浴びてから、寝ます。'),
(16, 3, 'N1 は N2 が A です', 'N1 có bộ phận hoặc đặc điểm N2 mang tính chất A.', 'ミラーさんは 背が 高いです。'),
(16, 4, 'Aいくて／Aな・Nで', 'Nối tính từ hoặc danh từ với nghĩa vừa... vừa... hoặc và.', '彼女は きれいで、頭が いいです。'),

(17, 1, 'Vない', 'Thể phủ định ngắn của động từ.', 'お酒を 飲まない。'),
(17, 2, 'Vないでください', 'Xin đừng làm V.', '窓を 開けないでください。'),
(17, 3, 'Vなければなりません', 'Phải làm V.', '今晩 勉強しなければなりません。'),
(17, 4, 'Vなくてもいいです', 'Không làm V cũng được.', '明日 会社へ 行かなくてもいいです。'),
(17, 5, 'N（thời gian）までに V', 'Hoàn thành V trước thời điểm N.', '来週までに レポートを 出さなければなりません。'),
(17, 6, 'Chủ đề hóa tân ngữ', 'Đưa tân ngữ lên làm chủ đề và thay を bằng は.', 'ラーメンは はしで 食べます。'),

(18, 1, 'Vる（thể từ điển）', 'Cách chia động từ sang thể từ điển.', '行きます → 行く。'),
(18, 2, 'N／Vることが できます', 'Có thể làm V hoặc có khả năng về N.', 'ピアノを 弾くことが できます。'),
(18, 3, '私のしゅみは～です', 'Sở thích của ai đó là gì.', 'ゆきさんの しゅみは つりです。'),
(18, 4, 'Nの前に／N前に／Vる前に', 'Diễn tả trước một sự việc, thời điểm hoặc hành động.', '毎日 寝る前に 本を 読みます。'),

(19, 1, 'Vた', 'Thể ngắn quá khứ của động từ.', '行きます → 行った。'),
(19, 2, 'Vたことが あります', 'Đã từng làm V.', '広島へ お花見に 行ったことが あります。'),
(19, 3, 'V1たり、V2たりします', 'Liệt kê một số hành động đã hoặc thường thực hiện.', 'もみじを 見たり、金閣寺へ 行ったりしました。'),
(19, 4, 'Aな／N に なります', 'Trở nên hoặc trở thành A hay N.', '英語の 先生に なりたいです。'),

(20, 1, 'Thể thông thường', 'Dạng thông thường của động từ, tính từ và danh từ ở hiện tại, tương lai và quá khứ.', 'Vます → Vる、Vません → Vない、Vました → Vた。'),

(21, 1, 'Thể thông thường と 思います', 'Tôi nghĩ hoặc đoán rằng.', '部長は 彼女が いると思います。'),
(21, 2, 'Ngườiに câu と 言います', 'Nói với ai đó rằng.', '「いってきます」と 言います。'),
(21, 3, 'Aい／Aな／N でしょう', 'Xác nhận điều người nói cho là đúng: phải không?', '今日は 暑いでしょう。'),
(21, 4, 'Nでも V', 'Đề xuất một thứ đại diện với nghĩa như là hoặc gì đó như.', '今晩 焼き肉でも 食べませんか。'),

(22, 1, 'V（thể thường）＋N', 'Động từ bổ nghĩa cho danh từ.', 'レストランで 食べた料理。'),
(22, 2, 'S は V（thể thường）＋N です', 'Cụm danh từ làm vị ngữ.', 'これは 妻に もらった時計です。'),
(22, 3, 'V（thể thường）＋N は～', 'Danh từ được bổ nghĩa trở thành chủ đề.', 'レストランで 食べた料理は おいしかったです。'),
(22, 4, 'S は（bổ nghĩa）N を／が～', 'Cụm danh từ làm tân ngữ hoặc thành phần với が.', '私は 大きい台所が ある家が 欲しいです。'),

(23, 1, 'Vる／Vない／Vた・Aい・Aな・N のとき', 'Khi, lúc hoặc hồi một sự việc xảy ra.', '22歳のとき、初めて 夫に 会いました。'),
(23, 2, 'Vると、～', 'Hễ hoặc cứ làm V thì kết quả tất yếu xảy ra.', 'お酒を 飲むと 頭が いたくなります。'),

(24, 1, 'A は 私に N を くれます', 'A cho hoặc tặng tôi N.', '山田さんは 妹に 花をくれました。'),
(24, 2, 'A は 私に Vてくれます', 'A làm V cho tôi.', 'ナムさんが 傘を 貸してくれました。'),
(24, 3, 'A は B に Vてもらいます', 'A được B làm V cho.', 'わたしは 母に ケーキの 作り方を 教えてもらいました。'),
(24, 4, 'A は B に Vてあげます', 'A làm V cho B.', '山田さんは アンさんに 荷物を 運んであげます。'),

(25, 1, '～たら（điều kiện）', 'Nếu điều kiện phía trước xảy ra thì có kết quả phía sau.', '暇だったら、遊びに 来てください。'),
(25, 2, '～たら（thời điểm）', 'Sau khi hoặc đến khi sự việc phía trước xảy ra thì làm việc phía sau.', '駅に 着いたら、私に 電話してください。'),
(25, 3, '～ても', 'Cho dù hoặc dẫu điều kiện phía trước xảy ra thì kết quả vẫn không đổi.', '考えても、わかりません。');

INSERT INTO course_content (
    section_id, title, summary, content_html, content_type,
    display_order, is_preview, publication_status
)
SELECT
    section.id,
    grammar.grammar_pattern,
    grammar.meaning_text,
    CONCAT(
        '<p><strong>Công thức:</strong> ', grammar.grammar_pattern, '</p>',
        '<p><strong>Ý nghĩa:</strong> ', grammar.meaning_text, '</p>',
        CASE
            WHEN grammar.example_text IS NULL THEN ''
            ELSE CONCAT('<p><strong>Ví dụ:</strong> ', grammar.example_text, '</p>')
        END
    ),
    'GRAMMAR',
    grammar.item_order,
    TRUE,
    'PUBLISHED'
FROM minna_n5_grammar_seed grammar
JOIN course_section section
  ON section.course_id = @minna_n5_course_id
 AND section.display_order = grammar.lesson_number
WHERE NOT EXISTS (
    SELECT 1
    FROM course_content existing_content
    WHERE existing_content.section_id = section.id
      AND existing_content.display_order = grammar.item_order
);

DROP TEMPORARY TABLE minna_n5_grammar_seed;

COMMIT;

SELECT
    course.id,
    course.course_code,
    COUNT(DISTINCT section.id) AS section_count,
    COUNT(content.id) AS content_count
FROM course
LEFT JOIN course_section section ON section.course_id = course.id
LEFT JOIN course_content content ON content.section_id = section.id
WHERE course.course_code = 'JA-MINNA-N5-GRAMMAR'
GROUP BY course.id, course.course_code;
